theme = "hugo-theme-bootstrap4-blog" 
baseURL = "https://www.beejblog.com/"
pygmentsCodeFences = true
title = "/* BeejBlog */"
disqusShortname = "beejblog"
pygmentsOptions = "linenos=table"

[params]
	favicon = "favicon.ico"